In [39]:
 import numpy as np

#letters JRE [10,18,5]
#letters AAS [1,1,19]

#matrix1
matrix1 = np.array([[10,18,5],[1,1,19]] )
print("MATRIX 1:\n", matrix1)

#first 3 SN digits [2,0,2]
#last 3 SN digits [4,8,2]

#matrix2
matrix2 = np.array([[2,0,2],[4,8,2]])
print("\nMATRIX 2:\n", matrix2)

#matrix addition
matrix3 = np.add(matrix1,matrix2)
print("\nMATRIX 3:\n", matrix3)

#scalar multiplication
matrix4 = np.multiply(matrix1,2)
print("\nMATRIX 4:\n", matrix4)

#matrix transpose
matrix5 = matrix2.T
print("\nMATRIX 5:\n", matrix5)

#matrix multiplication
matrix6 = np.dot(matrix3,matrix5)
print("\nMATRIX 6:\n", matrix6)

#sum of all elements in matrix3
sum_matrix3 = np.sum(matrix3)
print("\nsum of all elements in matrix3:\n", sum_matrix3)

#zero matrix
matrix7 = np.zeros((2,3))
print("\nMATRIX 7:\n", matrix7)


MATRIX 1:
 [[10 18  5]
 [ 1  1 19]]

MATRIX 2:
 [[2 0 2]
 [4 8 2]]

MATRIX 3:
 [[12 18  7]
 [ 5  9 21]]

MATRIX 4:
 [[20 36 10]
 [ 2  2 38]]

MATRIX 5:
 [[2 4]
 [0 8]
 [2 2]]

MATRIX 6:
 [[ 38 206]
 [ 52 134]]

sum of all elements in matrix3:
 72

MATRIX 7:
 [[0. 0. 0.]
 [0. 0. 0.]]
